### ISSUE TITLE
Implementing script when having multiple platforms

### ISSUE THREAD

**Issue by pjansen75** [steve228uk/homebridge-magichome#19]
Hello,
I hope you can help me out.
I have this config file:

> {
	"bridge": {
		"name": "Homebridge",
		"username": "CC:21:3E:E4:DE:33",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "KlikAanKlikUit",
		"driver": {
			"type": "rpi",
			"pin": 11
		},
		"accessories": [{
				"name": "Spotjes zolderkamer",
				"type": "Lightbulb",
				"dimmable": false,
				"address": "M",
				"device": 1
			},
			{
				"name": "LED lamp",
				"type": "Lightbulb",
				"dimmable": true,
				"address": 5201,
				"device": 2
			},
			{
				"name": "LEDstrip keuken",
				"type": "Lightbulb",
				"dimmable": true,
				"address": 5202,
				"device": 3
			}
		]
	}
	]
}

> 
Now I want to add this accessory into the config file:

> "accessories": [
   {
       "accessory": "MagicHome",
       "name": "LED Strip",
       "ip": "192.168.1.111",
       "setup": "RGBWW",
       "purewhite": false
   }
]

> 
Please, can you help me how to write a working config file for me?
Thanks in advance.

**Comment by Zacknetic** [comment]
Okay,  I have some questions before I can help you. 

What's your hardware that you want to add? Pictures help. Does it have RGB plus a dedicated cold white and a dedicated warm white?  

Have you installed the homebridge magichome plugin?

Lastly, homebridge magichome doesn't work perfectly with RGBWW (5 channel) lights. You will need to make some modifications or download my version of flux_led.py and index.js from github to get it to work.

Let me know

**Comment by pjansen75** [comment]
Thanks for your respons.
See picture of what kind of RGB controller I have, it's an UFO.
![ufo](https://user-images.githubusercontent.com/29973478/27982976-58645562-63b2-11e7-9ea4-d45c5940dea9.jpg)
In the meantime I managed to make a working config.json file, but I can not change color of the UFO. Then the config will crash and I have to reboot my RaspberryPi3. So, I need to make some modifications you suggest? Maybe, you can help me with that?
Thanks in advance.

**Comment by Zacknetic** [comment]
This doesn't help me at all. I have no idea what that thing is. There are
too many types of controllers for me to know what you have. Show me the
outputs of the device. Where and how do you plug it in. What kind of LEDs
are you using.  Join me on https://homebridgeteam.slack.com and add me
@lethegrin so we can speak in real time.

**Comment by pjansen75** [comment]
It is the same controller as in the discussion of "LEDENET UFO".
I found out that I have to use RGBWWv3 as setup value in the config.json. Then Homekit is stable. I connected a RGB led strip to this controller and it is working with the app "Magic Home" from the Appstore. Everything is working fine then, but I can not change color via Homekit. (Homebridge).
I hope this is enough information? :-)

**Comment by Zacknetic** [comment]
I don't use this controller but I'm willing to bet it works exactly like
the one I use seeing how you are getting the same problems I had.


*Step One: *
Delete everything in your config.json and replace it with this. Fix the IPs
as neccisary.


{
    "bridge": {
        "name": "MY COOL HOMEBRIDGE NAME",
        "username": "CC:54:3D:E3:CE:30",
        "port": 51826,
        "pin": "123-45-678"
    },

"accessories": [
  {
    "accessory": "MagicHome",
    "name": "Light 1",
    "ip": "192.168.1.111",
    "setup": "RGBWW",
    "purewhite": true
  },

  {
    "accessory": "MagicHome",
    "name": "Light 2",
    "ip": "192.168.1.222",
    "setup": "RGBWW",
    "purewhite": true
  }
]
}

*Step Two:*
Download my version of magichome here
https://github.com/Lethegrin/homebridge-magichome and extract flux_led.py
and index.js which fixes these lights for RGBWW 5 channel lights. If you
are downloading to a windows based system make sure your line endings don't
get converted to windows line endings. Make sure they are UNIX line endings
for both files. Replace both of these files in your homebridge-magichome
folder on your pie.Use the chmod command on flux_led.py so linux knows it's
an executable.

*Step Three:*
Restart homebridge


Your lights, if they are RGBWW, SHOULD have a dedicated warm white and a
dedicated cold white LED.  That's why I asked for the LED strip type.  A
picture of your actual LIGHTS not the controller would be useful.

Let me know if this works

**Comment by pjansen75** [comment]
Hi,
I tried what you asked me, but I get an error after I replaced the two files.
![img_1121](https://user-images.githubusercontent.com/29973478/27985099-f0d5351e-63e4-11e7-812a-47469538a330.JPG)

**Comment by Zacknetic** [comment]
You replaced these files in the homebridge-magichome folder right?  That is
located in /usr/local/lib/node_modules/homebridge_magichome . Sorry, it's
just so hard for me to know whats going on without seeing it directly.

**Comment by pjansen75** [comment]
Yes, that's right. I placed it there. 
I appreciate your efforts. Thank you.
