### ISSUE TITLE
Warm White

### ISSUE THREAD

**Issue by grstreten** [steve228uk/homebridge-magichome#4]
Setting the colour to warm white at the top of the colour temp wheel is not as warm as when using the MagicHome app - is there a way to resolve this? Many thanks.

**Comment by grstreten** [comment]
(I'm using this: https://www.amazon.com/MagicLight-WiFi-Smart-Light-Bulb/dp/B00SIDVZSW)

**Comment by steve228uk** [comment]
Currently there's only support for 100% (cold) white. I'll need to have a look to see if HomeKit has an option for temperature.

**Comment by grstreten** [comment]
Right gotcha - sick, thanks.

There is an option in the Home app, but not sure how that integrates... Screenshot attached :)

![img_1187](https://cloud.githubusercontent.com/assets/2766825/21963266/aba8482a-db2f-11e6-9f41-94d8dabad21b.PNG)

**Comment by jimbo-83** [comment]
Hey, be good to know what the outcome of this is as have 2 of these bulbs and have a similar issue

**Comment by DanBennettUK** [comment]
Wonder if anyone has any movement on this?

I have the same bulb, warm white on the app works perfectly. But via Homebridge white comes out as blue.

**Comment by jimbo-83** [comment]
Yep, me too. I have set my json with RGBWW and pure white to true, this disables all colours but does mean it will just hold the previous colour/setting I have set on the bulbs own app. It's a shame as it works ok but just needs someone who's in the know to play with the code a bit. Doesn't seem to be any development on it at the moment

**Comment by DanBennettUK** [comment]
Oddly, I've now been able to get it working with RGBW and purewhite set to 'true'. This wasn't working when I initially posted (using the SuperLegends Wi-Fi smart bulb) but having reinstalled the package it magically works.

Turns out the bulb has separate LEDs for the white (which are much brighter, too) and going to other colours works without fail.

So telling Siri to "Set my living room to white" works (though the non-purewhite LEDs just light all the RGB LEDs).

Now if only I could change it so when I say "white" my LED strip without the purewhite sets the RGBs slightly differently so it gives a warm white feel!

**Comment by steve228uk** [comment]
@DanBennettUK Yep, this is exactly how it should work. If HomeKit sends an HSL of 0,0,0 (white) then that command is intercepted and the warm white command sent to the bulb.

https://github.com/steve228uk/homebridge-magichome/blob/master/index.js#L114-L117
